DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS pixels;
DROP TABLE IF EXISTS userinfo;

CREATE TABLE messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    username TEXT CHECK (LENGTH(username) > 1 AND LENGTH(username) < 17),
    content TEXT NOT NULL CHECK (LENGTH(content) < 200)
);

CREATE TABLE pixels (
    x INTEGER NOT NULL,
    y INTEGER NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    colour TEXT,
    PRIMARY KEY (x, y)
);

CREATE TABLE IF NOT EXISTS userinfo (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE CHECK(LENGTH(username) >= 3 AND LENGTH(username) <= 16),
    password TEXT NOT NULL,
    creationTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    userType TEXT DEFAULT 'User'
);